### ISSUE TITLE
error running calculations on windows 

### ISSUE THREAD

**Issue by lmartins88** [gem/oq-engine#4756] opened 2019-05-28 12:45 UTC
Ciao Daniele, Michele

I was trying to run a small job (sending the job files in attachment) on my windows 10 laptop running OQ V3.5.1. and I got the error on the image. The job seems to run well on linux (I was able to run it on the P710). Can I have your feedback please. Have I done a mistake on my .ini file?

Cheers

L. Martins

![image](https://user-images.githubusercontent.com/25605716/58478661-e7583900-8156-11e9-935d-74b5ce4dcafa.png)
 
[oq_files.zip](https://github.com/gem/oq-engine/files/3227623/oq_files.zip)

**Comment by daniviga** [comment] 2019-05-28 12:58
See https://github.com/gem/oq-engine/pull/4757

**Comment by daniviga** [comment] 2019-05-28 13:27
Can you try this build? https://ci.openquake.org/job/builders/job/installers-builder/61/Node=master,OS=windows/artifact/oq-builders/installers/windows/nsis/OpenQuake_Engine_3.5.1-1905281305.exe

**Comment by lmartins88** [comment] 2019-05-28 13:38
Ciao Daniele,
this time it ran more than last time, but still got an error

![image](https://user-images.githubusercontent.com/25605716/58482393-96e4d980-815e-11e9-8fb8-d514503f443f.png)

**Comment by daniviga** [comment] 2019-05-28 13:59
That's an error for @micheles

**Comment by daniviga** [comment] 2019-05-28 14:05
Just see that input are attached, sorry

**Comment by daniviga** [comment] 2019-05-28 14:14
> The job seems to run well on linux (I was able to run it on the P710).

No, the problem is not related to the OS: on your machine you are running 3.5.1 meanwhile p710 is running a snapshot of master.
It looks like the bug has been fixed in current master. I was able to reproduce your issue with Engine 3.5 but not with master (Linux, indeed on).
You can use a master snapshot for windows (https://downloads.openquake.org/pkgs/windows/oq-engine/nightly/OpenQuake_Engine_3.6.0_1905272110.zip). Please note that snapshots do not require an installation, you need just to unzip the content of the downloaded file and then you have to execute `oq-console.bat`.

**Closed** 2019-05-28 14:19 UTC
Labels: bug, packaging, support
