### ISSUE TITLE
BSSA14 distance-dependent phi computation fails when Rjb > R2 

### ISSUE THREAD

**Issue by vSahakian** [gem/oq-engine#4243] opened 2018-11-27 19:03 UTC
In ~line 249 of boore_2014 in gsim, the following line fails when Rjb is larger than R2, because `idx2` will be False

```
base_vals[idx2] += (C["DfR"] * (np.log(rjb[idx2] / C["R1"]) /
                                        np.log(C["R2"] / C["R1"])))
```

Therefore, `np.log(rjb[idx2])` will be empty, and cannot be broadcast into `basevals`. 
Suggest replacing with the following in order to match Equation 16 of Boore et al. (2014):
```
if idx2 == True:
            base_vals[idx2] += (C["DfR"] * (np.log(rjb[idx2] / C["R1"]) /
                                        np.log(C["R2"] / C["R1"])))
```

**Comment by mmpagani** [comment] 2018-12-17 13:09
Thank you for this note and sorry for replying late. We've been busy with the release of the global hazard maps.

In order to further test the issue you signalled, we created a simple ad-hoc test that should be able to exercise this case.

```
import numpy as np
from openquake.hazardlib.const import StdDev
from openquake.hazardlib.imt import PGA
from openquake.hazardlib.contexts import DistancesContext
from openquake.hazardlib.tests.gsim.mgmpe.dummy import Dummy
from openquake.hazardlib.gsim.boore_2014 import BooreEtAl2014


def main():

    stddev_types = [StdDev.INTRA_EVENT]
    sitec = Dummy.get_site_collection(4, vs30=760.)
    dists = DistancesContext()
    dists.rjb = np.array([10, 50, 150, 300])
    rup = Dummy.get_rupture(mag=6.0)
    gsim = BooreEtAl2014()
    imt = PGA()
    mean, std = gsim.get_mean_and_stddevs(sitec, rup, dists, imt, stddev_types)
    print('std:', std)

if __name__ == '__main__':
    main()
```

In this example, `idx2` (https://github.com/gem/oq-engine/blob/master/openquake/hazardlib/gsim/boore_2014.py#L242) takes the following values: 
``` [False False  True False] ``` hence this instruction https://github.com/gem/oq-engine/blob/master/openquake/hazardlib/gsim/boore_2014.py#L243 is used only for 150 km.

If this is not explaining the issue you signalled please send us a test case that we can use to reproduce your problem.

**Comment by micheles** [comment] 2019-01-10 14:51
Closing since we good no feedback after 24 days.

**Closed by micheles** 2019-01-10 14:51 UTC
