### ISSUE TITLE
libhdf5 segfaults in Ubuntu 16.04

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#2103] opened 2016-06-16 14:17 UTC
Daniele was able to produce segfaults just downloading outputs from the event based calculation used in the WebUI tests.

**Comment by daniviga** [comment] 2016-06-16 16:32
I've been able to reproduce the error with HDF5 1.8.11 too:
```
[29242.268583] python[3800]: segfault at 30 ip 00007fe5e83db4f4 sp 00007fe5dd060058 error 4 in libhdf5.so.8.0.0[7fe5e8336000+2c8000]
```

**Comment by daniviga** [comment] 2016-06-16 16:33
Marked as bloker, I want to make more manual tests also on other Ubuntu releases and RHEL. Currently it's easy to break with a certain pattern.

**Comment by daniviga** [comment] 2016-06-16 16:55
With `h5py==2.2.1` same version of Trusty everything is ok. But every version >= 2.4 breaks the webui.

**Comment by daniviga** [comment] 2016-06-16 18:09
Summary:
- Ubuntu 12.04: not tested but should be OK (h5py < 2.2)
- Ubuntu 14.04: OK (h5py == 2.2)
- Ubuntu 16.04: NOT OK (h5py == 2.6)
- RHEL 7: OK (h5py == 2.3)
- opt: OK (downgraded to h5py == 2.2)

h5py 2.2 does not compile on HDF5 1.8.16 (too new), so I did not test this config, but I tested h5py 2.3 on HDF5 1.8.16 and this configuration works well, so the cause is **h5py** and **not libhdf5**.

**Closed** 2016-06-17 06:11 UTC
Labels: bug
